### Get token
POST {{keycloak}}/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

{{credentials}}

> {% client.global.set("auth_token", response.body.access_token); %}

### Get all organizations.
GET {{api}}
Authorization: Bearer {{auth_token}}

### Add an organization. Location response header will contain the new resource ID.
POST {{api}}
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "organizationId": "1130",
  "name": "Yet another one"
}

### Get an organization.
GET {{api}}/130
Authorization: Bearer {{auth_token}}

### Update an organization. The resource ID must exist.
PUT {{api}}/9631a9ae-fd44-408a-8df6-3904d403dada
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "id": "12345678",
  "name": "Hi Dad"
}
