### Get token
POST {{keycloak}}/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

{{credentials}}

> {% client.global.set("auth_token", response.body.access_token); %}

### Get all organizations.
GET {{api}}
Authorization: Bearer {{auth_token}}

### Add an organization. Location response header will contain the new resource ID.
POST {{api}}
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "organizationId": "12345",
  "name": "September 20th, 7:21PM"
}

### Get an organization.
GET {{api}}/130
Authorization: Bearer {{auth_token}}

### Update an organization. The resource ID must exist.
PUT {{api}}/1130
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "organizationId": "1130",
  "name": "Only three orgs still"
}
