spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${base-oauth-url}
          jwk-set-uri: ${base-oauth-url}/protocol/openid-connect/certs
server:
  port: 8082
#base-oauth-url: http://localhost:8080/realms/master
base-oauth-url: https://common-logon-dev.hlth.gov.bc.ca/auth/realms/moh_applications
