name: "Terraform"

on:
  workflow_dispatch

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    env:
        TFC_WORKSPACE: terraform-dev
        
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ~1.3.7
          cli_config_credentials_token: ${{ secrets.TFC_TEAM_TOKEN }}
          working-directory: ${{ env.TFC_WORKSPACE }}

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color -input=false
